import { FindingOwnersPanel } from "./finding-owners";
import { useState } from "react";
import { api, write, APIError } from "./api";
import { ErrorBox, date } from "./components";
import { useResource } from "./page-utils";
type Disposition={revision:number;status:string;reason:string;owner:number;expires_at:string;head_sha:string;actor:number;updated_at:string;manual_resolution:boolean};
type Report={current:Disposition;history:Disposition[];history_truncated:boolean;can_manage:boolean};
const labels:Record<string,string>={open:"待处理",accepted:"暂时接受风险",resolved:"人工确认修复",unknown:"证据不足"};
function DispositionEditor({runId,findingId}:{runId:number;findingId:string}){
 const resource=useResource<Report>(`/runs/${runId}/findings/${encodeURIComponent(findingId)}/disposition`);const [draft,setDraft]=useState<Disposition|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");const [assertion,setAssertion]=useState(false);const current=resource.data?.current;const value=draft||current;
 return <><ErrorBox error={error||resource.error}/>{resource.loading?<p>加载风险处理记录…</p>:!resource.error&&current&&value?<><p>当前：{labels[current.status]} · HEAD {current.head_sha.slice(0,12)} · 版本 {current.revision}</p><p>{current.reason}{current.owner?` · 责任人 #${current.owner}`:""}{current.expires_at?` · 到期 ${date(current.expires_at)}`:""}</p>
 <FindingOwnersPanel runId={runId} findingId={findingId} headSHA={value.head_sha} onChoose={resource.data?.can_manage&&!busy?owner=>{setDraft({...value,owner});setMessage("")}:undefined}/>
 {resource.data?.can_manage?<form className="integration-form" onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError("");setMessage("");try{await api(`/runs/${runId}/findings/${encodeURIComponent(findingId)}/disposition`,write("PUT",{expected_revision:value.revision,status:value.status,reason:value.reason,owner:value.owner,expires_at:value.expires_at,head_sha:value.head_sha,manual_resolution:value.status==="resolved"&&assertion}));setDraft(null);setAssertion(false);setMessage("风险处理决定已保存，旧记录保留。");await resource.load()}catch(e){setDraft({...value});setError(e instanceof APIError&&e.status===409?"记录或提交已变化，草稿已保留。请刷新后核对最新版本。":(e as Error).message);await resource.load()}finally{setBusy(false)}}}>
 <fieldset disabled={busy}><label>处理状态<select value={value.status} onChange={e=>{setDraft({...value,status:e.target.value});setAssertion(false)}}>{Object.entries(labels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>依据<textarea maxLength={4000} required={value.status!=="open"} value={value.reason} onChange={e=>setDraft({...value,reason:e.target.value})}/></label><label>责任人用户编号<input type="number" min="0" required={value.status==="accepted"} value={value.owner||""} onChange={e=>setDraft({...value,owner:Number(e.target.value)})}/></label>
 {value.status==="accepted"&&<label>到期时间（含时区，如 2026-11-01T09:00:00+08:00）<input required value={value.expires_at} onChange={e=>setDraft({...value,expires_at:e.target.value})}/></label>}
 {value.status==="resolved"&&<label><input type="checkbox" checked={assertion} onChange={e=>setAssertion(e.target.checked)}/>我已核对修复依据并明确确认；此决定是人工结论，不表示运行复现。</label>}
 <button disabled={busy||(value.status==="resolved"&&!assertion)||value.revision!==current.revision}>保存风险处理</button><button type="button" disabled={busy} onClick={()=>{setDraft({...current});setAssertion(false);setError("")}}>加载最新记录（替换草稿）</button></fieldset></form>:<p>当前权限可查看，风险处理需要项目操作权限。</p>}
 <details><summary>处理历史（{resource.data?.history.length}）</summary>{resource.data?.history.map(item=><p key={item.revision}>版本 {item.revision} · {labels[item.status]} · {item.actor?`用户 #${item.actor}`:"系统到期处理"} · {date(item.updated_at)} · {item.reason}{item.expires_at?` · 当时到期 ${date(item.expires_at)}`:""}</p>)}{resource.data?.history_truncated&&<p>仅展示最近 20 条历史。</p>}</details></>:null}<button disabled={busy} onClick={resource.load}>刷新处理记录</button>{message&&<p role="status">{message}</p>}</>;
}
export function FindingDispositionPanel(props:{runId:number;findingId:string}){const [opened,setOpened]=useState(false);return <details onToggle={e=>{if(e.currentTarget.open)setOpened(true)}}><summary>风险处理与到期记录</summary><p>与人工复核分开记录；风险接受只适用于本次固定提交，不继承到新提交。</p>{opened&&<DispositionEditor {...props}/>}</details>}
